default_db: crypto
str: "mongodb://10.201.8.215:27017"
username: ""
password: ""

db_name:
  crypto: "crypto"
  cn_stock: "cn_stock"
  us_share: "us_share"
  hk_share: "hk_share"
  fund: "fund"
  option: "option"
  future: "future"
