defaults:
  - _self_
  - db: mongodb

proxy:
  enable: True
  http: http://10.201.8.104:18443
  https: http://10.201.8.104:7890
  socks5: socks5://10.201.8.104:7890

output:
  dir: "./logs/"

datasource:
  timezone: Asia/Shanghai
  crypto: true
  cn_share: true
  us_share: true
  hk_share: true
  fund: true

dns:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

check_ip: false
update_crypto: false
update_cn_stock: false
update_all: false
